### ISSUE TITLE
Words can overflow window width 

### ISSUE THREAD

**Issue by gerazov** [NStefan002/speedtyper.nvim#21]
This is especially visible for narrower windows:

![image](https://github.com/NStefan002/speedtyper.nvim/assets/15214418/5f837767-2e3e-4215-b8d6-e237fc0b80c6)

**Comment by NStefan002** [comment]
I think the solution you proposed in #22 does not fix the problem. The original solution is bad because of the magic constant. `nvim_win_get_width` gets the width expressed in columns. The problem is that is not the 'writable' number of columns, but the 'writable' columns + border width (I guess). By 'writable' I mean the number of columns that could contain text if that makes sense. This needs rework.

**Comment by NStefan002** [comment]
Do you mind testing this PR #23? It seems good to me.

**Comment by gerazov** [comment]
Среќна нова! :christmas_tree: 

This fits the text in but doesn't work well for sentence mode since it doesn't decrement the `next_word_id` so the edge words get skipped:

![image](https://github.com/NStefan002/speedtyper.nvim/assets/15214418/1eab2402-9e30-4590-8909-ed386bc34db8)

The sentence is `Now please give a plain statement of what occurred.`

I've modified the equation for the check based on `border_width` as you suggested to my PR. :+1:

**Comment by NStefan002** [comment]
Срећни празници!

Thanks, this should work!
